### ISSUE TITLE
Errors with Node 0.9.4

### ISSUE THREAD

**Issue by balupton** [benmills/robotskirt#26]
Get the following on my Macbook Air 2010 (running OSX Mountain Lion) and Node 0.9.4:

```
$ npm install robotskirt
npm http GET https://registry.npmjs.org/robotskirt
npm http 304 https://registry.npmjs.org/robotskirt
npm http GET https://registry.npmjs.org/robotskirt/-/robotskirt-2.7.1.tgz
npm http 200 https://registry.npmjs.org/robotskirt/-/robotskirt-2.7.1.tgz

> robotskirt@2.7.1 install /Users/balupton/Projects/docpad-website-merged/node_modules/robotskirt
> node-gyp rebuild

gyp http GET http://nodejs.org/dist/v0.9.4/node-v0.9.4.tar.gz
gyp http 200 http://nodejs.org/dist/v0.9.4/node-v0.9.4.tar.gz
  CC(target) Release/obj.target/sundown/src/autolink.o
  CC(target) Release/obj.target/sundown/src/buffer.o
  CC(target) Release/obj.target/sundown/src/houdini_href_e.o
  CC(target) Release/obj.target/sundown/src/houdini_html_e.o
  CC(target) Release/obj.target/sundown/src/houdini_html_u.o
In file included from ../src/houdini_html_u.c:6:
html_unescape.gperf:122:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
               ^
html_unescape.gperf:122:28: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
                           ^
html_unescape.gperf:122:40: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
                                       ^
html_unescape.gperf:122:52: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
                                                   ^
html_unescape.gperf:123:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
               ^
html_unescape.gperf:123:28: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
                           ^
html_unescape.gperf:123:40: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
                                       ^
html_unescape.gperf:123:52: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
                                                   ^
html_unescape.gperf:124:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0},
               ^
html_unescape.gperf:124:28: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0},
                           ^
html_unescape.gperf:133:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0},
               ^
html_unescape.gperf:133:28: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0},
                           ^
html_unescape.gperf:133:40: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0},
                                       ^
html_unescape.gperf:227:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0},
               ^
html_unescape.gperf:231:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0},
               ^
html_unescape.gperf:111:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0},
               ^
html_unescape.gperf:126:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0},
               ^
html_unescape.gperf:126:28: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0},
                           ^
html_unescape.gperf:16:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0},
               ^
html_unescape.gperf:80:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0},
               ^
html_unescape.gperf:80:28: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0},
                           ^
html_unescape.gperf:62:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0},
               ^
html_unescape.gperf:62:28: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0},
                           ^
html_unescape.gperf:13:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0},
               ^
html_unescape.gperf:84:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0},
               ^
html_unescape.gperf:52:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0},
               ^
html_unescape.gperf:244:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0},
               ^
html_unescape.gperf:244:28: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0},
                           ^
html_unescape.gperf:244:40: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0},
                                       ^
html_unescape.gperf:230:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0},
               ^
html_unescape.gperf:160:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0},
               ^
html_unescape.gperf:125:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0},
               ^
html_unescape.gperf:125:28: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0},
                           ^
html_unescape.gperf:125:40: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0},
                                       ^
html_unescape.gperf:55:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0},
               ^
html_unescape.gperf:55:28: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0},
                           ^
html_unescape.gperf:17:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0},
               ^
html_unescape.gperf:58:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0},
               ^
html_unescape.gperf:58:28: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0},
                           ^
html_unescape.gperf:201:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0},
               ^
html_unescape.gperf:226:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0},
               ^
html_unescape.gperf:61:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0},
               ^
html_unescape.gperf:61:28: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0},
                           ^
html_unescape.gperf:199:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0},
               ^
html_unescape.gperf:82:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0},
               ^
html_unescape.gperf:10:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0},
               ^
html_unescape.gperf:37:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0},
               ^
html_unescape.gperf:37:28: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0},
                           ^
html_unescape.gperf:251:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0},
               ^
html_unescape.gperf:114:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0},
               ^
html_unescape.gperf:182:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0},
               ^
html_unescape.gperf:171:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0},
               ^
html_unescape.gperf:49:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0},
               ^
html_unescape.gperf:180:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0},
               ^
html_unescape.gperf:180:28: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0},
                           ^
html_unescape.gperf:18:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0},
               ^
html_unescape.gperf:18:28: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0},
                           ^
html_unescape.gperf:18:40: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0},
                                       ^
html_unescape.gperf:220:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0},
               ^
html_unescape.gperf:220:28: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0},
                           ^
html_unescape.gperf:209:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0},
               ^
html_unescape.gperf:118:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0},
               ^
html_unescape.gperf:245:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0},
               ^
html_unescape.gperf:89:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0},
               ^
html_unescape.gperf:56:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0},
               ^
html_unescape.gperf:100:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0},
               ^
html_unescape.gperf:100:28: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0},
                           ^
html_unescape.gperf:100:40: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0},
                                       ^
html_unescape.gperf:40:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0},
               ^
html_unescape.gperf:204:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0},
               ^
html_unescape.gperf:207:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0},
               ^
html_unescape.gperf:206:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0},
               ^
html_unescape.gperf:29:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0},
               ^
html_unescape.gperf:29:28: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0},
                           ^
html_unescape.gperf:29:40: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0},
                                       ^
html_unescape.gperf:186:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0},
               ^
html_unescape.gperf:102:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0},
               ^
html_unescape.gperf:134:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0},
               ^
html_unescape.gperf:175:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0},
               ^
html_unescape.gperf:208:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0},
               ^
html_unescape.gperf:115:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0},
               ^
html_unescape.gperf:45:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0},
               ^
html_unescape.gperf:174:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0},
               ^
html_unescape.gperf:34:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0},
               ^
html_unescape.gperf:34:28: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0},
                           ^
html_unescape.gperf:34:40: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0},
                                       ^
html_unescape.gperf:132:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0},
               ^
html_unescape.gperf:132:28: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0},
                           ^
html_unescape.gperf:167:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0},
               ^
html_unescape.gperf:68:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
               ^
html_unescape.gperf:68:28: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
                           ^
html_unescape.gperf:68:40: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
                                       ^
html_unescape.gperf:68:52: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
                                                   ^
html_unescape.gperf:69:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0},
               ^
html_unescape.gperf:221:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
               ^
html_unescape.gperf:221:28: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
                           ^
html_unescape.gperf:221:40: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
                                       ^
html_unescape.gperf:221:52: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
                                                   ^
html_unescape.gperf:222:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0},
               ^
html_unescape.gperf:222:28: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0},
                           ^
html_unescape.gperf:222:40: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0},
                                       ^
html_unescape.gperf:63:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
               ^
html_unescape.gperf:63:28: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
                           ^
html_unescape.gperf:63:40: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
                                       ^
html_unescape.gperf:63:52: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
                                                   ^
html_unescape.gperf:121:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0},
               ^
html_unescape.gperf:121:28: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0},
                           ^
html_unescape.gperf:121:40: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0},
                                       ^
html_unescape.gperf:53:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
               ^
html_unescape.gperf:53:28: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
                           ^
html_unescape.gperf:53:40: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
                                       ^
html_unescape.gperf:53:52: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
                                                   ^
html_unescape.gperf:54:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
               ^
html_unescape.gperf:54:28: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
                           ^
html_unescape.gperf:54:40: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
                                       ^
html_unescape.gperf:54:52: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
                                                   ^
html_unescape.gperf:55:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
               ^
html_unescape.gperf:55:28: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
                           ^
html_unescape.gperf:55:40: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
                                       ^
html_unescape.gperf:55:52: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
                                                   ^
html_unescape.gperf:56:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0},
               ^
html_unescape.gperf:56:28: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0},
                           ^
html_unescape.gperf:56:40: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0},
                                       ^
html_unescape.gperf:57:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
               ^
html_unescape.gperf:57:28: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
                           ^
html_unescape.gperf:57:40: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
                                       ^
html_unescape.gperf:57:52: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
                                                   ^
html_unescape.gperf:58:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0},
               ^
html_unescape.gperf:58:28: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0},
                           ^
html_unescape.gperf:58:40: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0},
                                       ^
html_unescape.gperf:176:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
               ^
html_unescape.gperf:176:28: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
                           ^
html_unescape.gperf:176:40: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
                                       ^
html_unescape.gperf:176:52: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
                                                   ^
html_unescape.gperf:177:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
               ^
html_unescape.gperf:177:28: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
                           ^
html_unescape.gperf:177:40: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
                                       ^
html_unescape.gperf:177:52: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
                                                   ^
html_unescape.gperf:178:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0},
               ^
html_unescape.gperf:233:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
               ^
html_unescape.gperf:233:28: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
                           ^
html_unescape.gperf:233:40: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
                                       ^
html_unescape.gperf:233:52: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
                                                   ^
html_unescape.gperf:210:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
               ^
html_unescape.gperf:210:28: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
                           ^
html_unescape.gperf:210:40: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
                                       ^
html_unescape.gperf:210:52: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
                                                   ^
html_unescape.gperf:211:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
               ^
html_unescape.gperf:211:28: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
                           ^
html_unescape.gperf:211:40: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
                                       ^
html_unescape.gperf:211:52: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
                                                   ^
html_unescape.gperf:212:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
               ^
html_unescape.gperf:212:28: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
                           ^
html_unescape.gperf:212:40: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
                                       ^
html_unescape.gperf:212:52: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
                                                   ^
html_unescape.gperf:213:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
               ^
html_unescape.gperf:213:28: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
                           ^
html_unescape.gperf:213:40: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
                                       ^
html_unescape.gperf:213:52: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
                                                   ^
html_unescape.gperf:214:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
               ^
html_unescape.gperf:214:28: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
                           ^
html_unescape.gperf:214:40: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
                                       ^
html_unescape.gperf:214:52: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
                                                   ^
html_unescape.gperf:172:16: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
               ^
html_unescape.gperf:172:28: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
                           ^
html_unescape.gperf:172:40: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
                                       ^
html_unescape.gperf:172:52: warning: missing field 'utf8_len' initializer [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
                                                   ^
167 warnings generated.
  CC(target) Release/obj.target/sundown/src/houdini_js_e.o
  CC(target) Release/obj.target/sundown/src/houdini_js_u.o
  CC(target) Release/obj.target/sundown/src/houdini_uri_e.o
  CC(target) Release/obj.target/sundown/src/houdini_uri_u.o
  CC(target) Release/obj.target/sundown/src/houdini_xml_e.o
  CC(target) Release/obj.target/sundown/src/html.o
  CC(target) Release/obj.target/sundown/src/html_smartypants.o
  CC(target) Release/obj.target/sundown/src/markdown.o
  CC(target) Release/obj.target/sundown/src/stack.o
  LIBTOOL-STATIC Release/sundown.a
  CXX(target) Release/obj.target/robotskirt/src/robotskirt.o
  SOLINK_MODULE(target) Release/robotskirt.node
  SOLINK_MODULE(target) Release/robotskirt.node: Finished
robotskirt@2.7.1 node_modules/robotskirt
```

When installed via bevry/docpad-plugin-robotskirt we get:

```
> robotskirt@2.6.1 install /Users/balupton/Projects/docpad-website-merged/node_modules/docpad-plugin-robotskirt/node_modules/robotskirt
> node-waf clean ; node-waf configure build
Traceback (most recent call last):
  File "/usr/local/bin/node-waf", line 14, in <module>
    import Scripting
ImportError: No module named Scripting
Traceback (most recent call last):
  File "/usr/local/bin/node-waf", line 14, in <module>
    import Scripting
ImportError: No module named Scripting
npm ERR! robotskirt@2.6.1 install: `node-waf clean ; node-waf configure build`
npm ERR! `sh "-c" "node-waf clean ; node-waf configure build"` failed with 1
npm ERR! 
npm ERR! Failed at the robotskirt@2.6.1 install script.
npm ERR! This is most likely a problem with the robotskirt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-waf clean ; node-waf configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls robotskirt
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 12.2.0
npm ERR! command "/Users/balupton/.nvm/v0.9.4/bin/node" "/Users/balupton/.nvm/v0.9.4/bin/npm" "install"
npm ERR! cwd /Users/balupton/Projects/docpad-website-merged
npm ERR! node -v v0.9.4
npm ERR! npm -v 1.1.70
npm ERR! code ELIFECYCLE
```

**Comment by mildsunrise** [comment]
Well, first of all, there are two things to clear here:
1. You're mixing two versions. Version **2.7+** (first log) uses the preferred Node-GYP to compile,
   so it installs correctly (but with some warnings).
2. Version **2.6** and older (second log) use the old, antiquated Node-WAF to compile,
   so it fails in Node 0.9.

Therefore, the installation was successful in your first try!
But it fails on the second because docpad-plugin-robotskirt uses the old version.

---

Try to play around with a fresh install (`[sudo] npm install -g robotskirt`).
For example, run `node` and try to `require('robotskirt')`...

Tell me if you don't understand something I said.

**Comment by balupton** [comment]
Cool thanks. Yeah turns out if you change your node version, you gotta reinstall robotskirt. Cheers.
