### ISSUE TITLE
Install error with command "sudo npm install -g robotskirt"

### ISSUE THREAD

**Issue by siemenliu** [benmills/robotskirt#28]
<pre>
siemenliu-mbp:tmp liusiemen$ sudo npm install -g robotskirt
npm http GET https://registry.npmjs.org/robotskirt
npm http 304 https://registry.npmjs.org/robotskirt
/usr/local/bin/robotskirt -> /usr/local/lib/node_modules/robotskirt/bin/robotskirt

> robotskirt@2.7.1 install /usr/local/lib/node_modules/robotskirt
> node-gyp rebuild

  CC(target) Release/obj.target/sundown/src/autolink.o
mkdir: Release/obj.target/sundown/src/: Permission denied
mkdir: ./Release/.deps/Release/obj.target/sundown/src/: Permission denied
make: *** [Release/obj.target/sundown/src/autolink.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:215:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:99:17)
gyp ERR! stack     at Process._handle.onexit (child_process.js:678:10)
gyp ERR! System Darwin 12.2.1
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/robotskirt
gyp ERR! node -v v0.8.16
gyp ERR! node-gyp -v v0.6.3
gyp ERR! not ok 
npm ERR! robotskirt@2.7.1 install: `node-gyp rebuild`
npm ERR! `sh "-c" "node-gyp rebuild"` failed with 1
npm ERR! 
npm ERR! Failed at the robotskirt@2.7.1 install script.
npm ERR! This is most likely a problem with the robotskirt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls robotskirt
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 12.2.1
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g" "robotskirt"
npm ERR! cwd /Users/liusiemen/tmp
npm ERR! node -v v0.8.16
npm ERR! npm -v 1.1.48
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/liusiemen/tmp/npm-debug.log
npm ERR! not ok code 0
</pre>

**Comment by siemenliu** [comment]
reinstall node can solve.
