### ISSUE TITLE
install failure on OS X 10.8.4

### ISSUE THREAD

**Issue by mikejt** [benmills/robotskirt#30]
a whole bunch of:

```
html_unescape.gperf:172:52: warning: missing field 'utf8_len' initializer
      [-Wmissing-field-initializers]
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
                                               ^
```

Followed by:

```
  CC(target) Release/obj.target/sundown/src/houdini_js_e.o
  CC(target) Release/obj.target/sundown/src/houdini_js_u.o
  CC(target) Release/obj.target/sundown/src/houdini_uri_e.o
  CC(target) Release/obj.target/sundown/src/houdini_uri_u.o
  CC(target) Release/obj.target/sundown/src/houdini_xml_e.o
  CC(target) Release/obj.target/sundown/src/html.o
  CC(target) Release/obj.target/sundown/src/html_smartypants.o
  CC(target) Release/obj.target/sundown/src/markdown.o
  CC(target) Release/obj.target/sundown/src/stack.o
  LIBTOOL-STATIC Release/sundown.a
libtool: unrecognized option `-static'
libtool: Try `libtool --help' for more information.
make: *** [Release/sundown.a] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:754:12)
gyp ERR! System Darwin 12.4.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/robotskirt
gyp ERR! node -v v0.10.0
gyp ERR! node-gyp -v v0.9.5
gyp ERR! not ok 
npm ERR! robotskirt@2.7.1 install: `node-gyp rebuild`
npm ERR! `sh "-c" "node-gyp rebuild"` failed with 1
npm ERR! 
npm ERR! Failed at the robotskirt@2.7.1 install script.
npm ERR! This is most likely a problem with the robotskirt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls robotskirt
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 12.4.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g" "robotskirt"
npm ERR! cwd /Users/mikejt/dp-ws
npm ERR! node -v v0.10.0
npm ERR! npm -v 1.2.18
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/mikejt/dp-ws/npm-debug.log
npm ERR! not ok code 0
```

**Comment by mikejt** [comment]
closed by accident

**Comment by mildsunrise** [comment]
Hmm, everything seems correct.
This seems more like a Node-GYP problem.
Maybe we're using it in a bad way?

**Comment by mildsunrise** [comment]
@TooTallNate please, help!
It seems Node-GYP is invoking Libtool incorrectly:

```
LIBTOOL-STATIC Release/sundown.a
libtool: unrecognized option -static'
libtool: Trylibtool --help' for more information.
```

An excerpt of [our `binding.gyp`](https://github.com/benmills/robotskirt/blob/master/binding.gyp):

``` json
{ "targets": [

    {
      "target_name": "sundown",
      "type": "static_library",
      "include_dirs": ["src"],
      "sources": [
        "src/autolink.c",
        "src/buffer.c",
        ...
      ]
    },

    {
      "target_name": "robotskirt",
      "sources": ["src/robotskirt.cc"],
      "dependencies": ["sundown"],

      "cflags": ["-Wall"],

      # enable exceptions
      ...
    }

] }
```

**Comment by TooTallNate** [comment]
You need to use the `libtool` that comes with OS X, not the one installed from Homebrew or whatever.

**Comment by mildsunrise** [comment]
timed out.
