### ISSUE TITLE
Failure on 'node-gyp rebuild' 

### ISSUE THREAD

**Issue by bdougie** [benmills/robotskirt#36]
I got the error when I cloned the repo to get ready to debug locally. Any info to help debug this is greatly appreciated.

Also, Is this repo still being support? [deprecation commit? (for docpad)](https://github.com/docpad/docpad-plugin-robotskirt/commit/c183c9b74c40c0546a939b8d4c6119db88106e31). Last commit to main repo was 11/2013.

Thanks for you help and hard work.

```
570 verbose pkgid robotskirt@2.7.1
571 verbose cwd /Users/bdoug/Desktop/marked
572 error Darwin 14.4.0
573 error argv "node" "/usr/local/bin/npm" "install"
574 error node v0.12.0
575 error npm  v2.5.1
576 error code ELIFECYCLE
577 error robotskirt@2.7.1 install: `node-gyp rebuild`
577 error Exit status 1
578 error Failed at the robotskirt@2.7.1 install script 'node-gyp rebuild'.
578 error This is most likely a problem with the robotskirt package,
578 error not with npm itself.
578 error Tell the author that this fails on your system:
578 error     node-gyp rebuild
578 error You can get their info via:
578 error     npm owner ls robotskirt
578 error There is likely additional logging output above.
579 verbose exit [ 1, true ]
580 verbose unbuild node_modules/robotskirt
581 info preuninstall robotskirt@2.7.1
582 info uninstall robotskirt@2.7.1
583 verbose unbuild rmStuff robotskirt@2.7.1 from /Users/bdoug/Desktop/marked/node_modules
584 verbose gentlyRm verifying that /Users/bdoug/Desktop/marked is managed by npm
585 silly isManaged /Users/bdoug/Desktop/marked is not inside /Users/bdoug/Desktop/marked/node_modules
586 silly isManaged /Users/bdoug/Desktop/marked is not inside /Users/bdoug/Desktop/marked/node_modules
587 silly isManaged /Users/bdoug/Desktop/marked/node_modules/.bin is inside /Users/bdoug/Desktop/marked
588 silly gentlyRm /Users/bdoug/Desktop/marked is managed by npm
589 silly gentlyRm /Users/bdoug/Desktop/marked/node_modules/.bin/robotskirt is under /Users/bdoug/Desktop/marked
590 verbose gentlyRm vacuuming /Users/bdoug/Desktop/marked/node_modules/.bin/robotskirt up to /Users/bdoug/Desktop/marked
591 silly gentlyRm removing /Users/bdoug/Desktop/marked/node_modules/.bin/robotskirt
592 silly gentlyRm quitting because other entries in /Users/bdoug/Desktop/marked/node_modules/.bin
593 info postuninstall robotskirt@2.7.1
594 verbose gentlyRm vacuuming /Users/bdoug/Desktop/marked/node_modules/robotskirt
595 silly gentlyRm purging /Users/bdoug/Desktop/marked/node_modules/robotskirt
596 silly gentlyRm quitting because other entries in /Users/bdoug/Desktop/marked/node_modules
```

When I run `node-gyp rebuild` in the repo
// [full error log can be found here](https://gist.github.com/brianllamar/855ca516e3c72abdbd90)

```
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/robotskirt/src/robotskirt.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.4.0
gyp ERR! command "node" "/usr/local/bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/bdoug/Desktop/robotskirt
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 

```

**Comment by bdougie** [comment]
I found my answer in [Issues 35](https://github.com/benmills/robotskirt/issues/35)

moving on to [hoedown](https://github.com/hoedown/hoedown). Please close this issue, Also thanks for the hardwork in creating this.

**Comment by mildsunrise** [comment]
I haven't put a deprecation notice [yet] because node-hoedown still doesn't offer the same functionality as this module, but yeah it's unmaintained and should be avoided.

**Comment by bdougie** [comment]
What is the latest version of node hoedown works on, 0.10?

**Comment by mildsunrise** [comment]
node-hoedown should work on 0.12 without problems, and maybe even 0.13 but I haven't tried it yet.
